# While the GitHub mirror is read-only, we keep this CI config
# for convenience to forks and pull requests.
#
# To submit a patch you can:
#
# * Create a Wikimedia Developer account and submit it to Wikimedia Gerrit
#   <https://www.mediawiki.org/wiki/Developer_account>,
#
# * Or, submit the output of `git diff origin/HEAD`
#   via <https://gerrit-patch-uploader.toolforge.org/>.
#
# * Or, create a pull request via GitHub and wait for someone
#   else to do one of the above.
#
name: Test

on:
  - push
  - pull_request

jobs:

  php:
    name: PHP ${{ matrix.php }}

    strategy:
      fail-fast: false
      matrix:
        include:
          # Includes php 8.3 and composer 2
          # https://github.com/actions/runner-images/blob/ubuntu24/20250105.1/images/ubuntu/Ubuntu2404-Readme.md#php-tools
          - php: '7.4'
            os: ubuntu-24.04
          - php: '8.0'
            os: ubuntu-24.04
          - php: '8.1'
            os: ubuntu-24.04
          - php: '8.2'
            os: ubuntu-24.04
          - php: '8.3'
            os: ubuntu-24.04
          - php: '8.4'
            os: ubuntu-24.04

    runs-on: ${{ matrix.os }}

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Use PHP ${{ matrix.php }}
      run: |
        sudo apt-add-repository ppa:ondrej/php -y
        sudo apt-get install -y -q php${{ matrix.php }} php${{ matrix.php }}-intl php${{ matrix.php }}-mbstring php${{ matrix.php }}-xml php${{ matrix.php }}-apcu php${{ matrix.php }}-curl php${{ matrix.php }}-xdebug
        php --version

    - name: Validate composer.json and composer.lock
      run: composer validate

    - name: Install dependencies
      run: composer install --prefer-dist --no-progress --no-suggest

    - name: Test
      run: composer test
